name: CI

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.2
          - 29.4
          - 30.2
          - snapshot
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@b8228894697c3cf9989a0e63977de4a239160628
      with:
        check: melpa
        file: erc-matterircd.el
    - uses: leotaku/elisp-check@b8228894697c3cf9989a0e63977de4a239160628
      with:
        check: ert
        file: test/erc-matterircd-test.el
