name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        export PATH="$HOME/bin:$PATH"
        wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
        make -f emacs-travis.mk install_cask
        cask install
        cask exec ert-runner
